<a href="https://colab.research.google.com/github/TheLiss/mlcourse_notebooks/blob/main/mlcourse_assignment__1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
DATA_URL = "https://raw.githubusercontent.com/Yorko/mlcourse.ai/main/data/"

In [ ]:
data = pd.read_csv(DATA_URL + "adult.data.csv")

In [ ]:
data.head(10)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K

In [ ]:
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

In [ ]:
data.groupby('sex').agg({'age': 'mean'})

              age
sex
Female  36.858230
Male    39.433547

In [ ]:
data['native-country'].value_counts(normalize=True)['Germany'] * 100

0.42074874850281013

In [ ]:
data.groupby('salary').agg({'age': 'mean'})

              age
salary
<=50K   36.783738
>50K    44.249841

In [ ]:
data.groupby('salary').agg({'age': 'std'})

              age
salary
<=50K   14.020088
>50K    10.519028

In [ ]:
data[data.salary=='>50K']['education'].value_counts()

education
Bachelors       2221
HS-grad         1675
Some-college    1387
Masters          959
Prof-school      423
Assoc-voc        361
Doctorate        306
Assoc-acdm       265
10th              62
11th              60
7th-8th           40
12th              33
9th               27
5th-6th           16
1st-4th            6
Name: count, dtype: int64

In [ ]:
data.groupby(['race', 'sex'])['age'].describe()

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

In [ ]:
data.groupby([data['marital-status'].str.contains('Married')])['salary'].value_counts(normalize=True)

marital-status  salary
False           <=50K     0.935546
                >50K      0.064454
True            <=50K     0.563080
                >50K      0.436920
Name: proportion, dtype: float64

In [ ]:
data['hours-per-week'].describe()

count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
Name: hours-per-week, dtype: float64

In [ ]:
data[data['hours-per-week']==99.00]['salary'].value_counts(normalize=True)

salary
<=50K    0.705882
>50K     0.294118
Name: proportion, dtype: float64

In [ ]:
data.groupby(['native-country', 'salary']).agg({'hours-per-week': 'mean'}).sort_values('hours-per-week', ascending=False)

                       hours-per-week
native-country salary
Honduras       >50K         60.000000
Thailand       >50K         58.333333
South          >50K         51.437500
France         >50K         50.750000
Greece         >50K         50.625000
...                               ...
El-Salvador    <=50K        36.030928
Peru           <=50K        35.068966
Honduras       <=50K        34.333333
Taiwan         <=50K        33.774194
Hungary        <=50K        31.300000

[82 rows x 1 columns]